package it.maggioli.eldasoft.gene.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-09-13T12:00:21.415+02:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(
		targetNamespace = "http://www.eldasoft.it/WSOperazioniGenerali/", 
		name = "WSOperazioniGeneraliSoap"
)
//@XmlSeeAlso({ObjectFactory.class})
public interface WSOperazioniGeneraliSoap {
	
	@WebMethod(operationName = "GetElencoTipiIndirizzo", action = "http://www.eldasoft.it/WSOperazioniGenerali/GetElencoTipiIndirizzo")
    public java.lang.String getElencoTipiIndirizzo();

    @WebMethod(operationName = "GetElencoOrganismiCertificatoriISO", action = "http://www.eldasoft.it/WSOperazioniGenerali/GetElencoOrganismiCertificatoriISO")    
    public java.lang.String getElencoOrganismiCertificatoriISO();

    @WebMethod(operationName = "GetElencoSettoriProduttivi", action = "http://www.eldasoft.it/sil/WSOperazioniGenerali/GetElencoSettoriProduttivi")    
    public java.lang.String getElencoSettoriProduttivi();

    @WebMethod(operationName = "GetDocumento", action = "http://www.eldasoft.it/WSOperazioniGenerali/GetDocumento")
    public it.maggioli.eldasoft.gene.ws.DocumentoOutType getDocumento(
        @WebParam(name = "idProgramma", targetNamespace = "")
        java.lang.String idProgramma,
        @WebParam(name = "idDocumento", targetNamespace = "")
        long idDocumento,
        @WebParam(name = "tokenRichiedente", targetNamespace = "")
        java.lang.String tokenRichiedente
    );

    @WebMethod(operationName = "GetUsernameDocumentoRiservato", action = "http://www.eldasoft.it/WSOperazioniGenerali/GetUsernameDocumentoRiservato")
    public String getUsernameDocumentoRiservato(
		@WebParam(name = "idProgramma", targetNamespace = "")
        java.lang.String idProgramma,
        @WebParam(name = "idDocumento", targetNamespace = "")
        long idDocumento
    );
        
    @WebMethod(operationName = "GetElencoTipiCassaPrevidenza", action = "http://www.eldasoft.it/WSOperazioniGenerali/GetElencoTipiCassaPrevidenza")    
    public java.lang.String getElencoTipiCassaPrevidenza();

    @WebMethod(operationName = "GetElencoComunicazioni", action = "http://www.eldasoft.it/WSOperazioniGenerali/GetElencoComunicazioni")    
    public it.maggioli.eldasoft.gene.ws.GetElencoComunicazioniOutType getElencoComunicazioni(
        @WebParam(name = "testata", targetNamespace = "")
        it.maggioli.eldasoft.gene.ws.DettaglioComunicazioneType testata
    );

    @WebMethod(operationName = "GetElencoTipiComunicazione", action = "http://www.eldasoft.it/sil/WSOperazioniGenerali/GetElencoTipiComunicazione")    
    public java.lang.String getElencoTipiComunicazione();

    @WebMethod(operationName = "GetElencoAliquoteIVA", action = "http://www.eldasoft.it/WSOperazioniGenerali/GetElencoAliquoteIVA")    
    public java.lang.String getElencoAliquoteIVA();

    @WebMethod(operationName = "GetElencoOrganismiCertificatoriSOA", action = "http://www.eldasoft.it/WSOperazioniGenerali/GetElencoOrganismiCertificatoriSOA")    
    public java.lang.String getElencoOrganismiCertificatoriSOA();

    @WebMethod(operationName = "GetElencoModalitaComunicazione", action = "http://www.eldasoft.it/WSOperazioniGenerali/GetElencoModalitaComunicazione")    
    public java.lang.String getElencoModalitaComunicazione();

    @WebMethod(operationName = "GetElencoProvince", action = "http://www.eldasoft.it/WSOperazioniGenerali/GetElencoProvince")    
    public java.lang.String getElencoProvince();

    @WebMethod(operationName = "GetElencoGradiAbilitazionePreventiva", action = "http://www.eldasoft.it/WSOperazioniGenerali/GetElencoGradiAbilitazionePreventiva")    
    public java.lang.String getElencoGradiAbilitazionePreventiva();

    @WebMethod(operationName = "ProtocollaComunicazione", action = "http://www.eldasoft.it/WSOperazioniGenerali/ProtocollaComunicazione")    
    public it.maggioli.eldasoft.gene.ws.ProtocollaComunicazioneOutType protocollaComunicazione(
        @WebParam(name = "applicativo", targetNamespace = "")
        java.lang.String applicativo,
        @WebParam(name = "id", targetNamespace = "")
        long id,
        @WebParam(name = "numeroProtocollo", targetNamespace = "")
        java.lang.String numeroProtocollo,
        @WebParam(name = "dataProtocollo", targetNamespace = "")
        java.util.Date dataProtocollo,
        @WebParam(name = "stato", targetNamespace = "")
        java.lang.String stato,
        @WebParam(name = "documento", targetNamespace = "")
        it.maggioli.eldasoft.gene.ws.WSDocumentoType documento,
        @WebParam(name = "allegato", targetNamespace = "")
        java.util.List<it.maggioli.eldasoft.gene.ws.WSAllegatoType> allegato
    );

/*    
//    @WebMethod(operationName = "ProtocollaComunicazione", action = "http://www.eldasoft.it/WSOperazioniGenerali/ProtocollaComunicazione")
//    public it.maggioli.eldasoft.gene.ws.ProtocollaComunicazioneOutType protocollaComunicazione(
//        @WebParam(name = "applicativo", targetNamespace = "")
//        java.lang.String applicativo,
//        @WebParam(name = "id", targetNamespace = "")
//        long id,
//        @WebParam(name = "numeroProtocollo", targetNamespace = "")
//        java.lang.String numeroProtocollo,
//        @WebParam(name = "dataProtocollo", targetNamespace = "")
//        Date dataProtocollo,
//        @WebParam(name = "stato", targetNamespace = "")
//        java.lang.String stato,
//        @WebParam(name = "documento", targetNamespace = "")
//        it.maggioli.eldasoft.gene.ws.WSDocumentoType documento,
//        @WebParam(name = "allegato", targetNamespace = "")
//        it.maggioli.eldasoft.gene.ws.WSAllegatoType[] allegato
//    );
*/    

    @WebMethod(operationName = "IsComunicazioneProcessata", action = "http://www.eldasoft.it/WSOperazioniGenerali/IsComunicazioneProcessata")    
    public it.maggioli.eldasoft.gene.ws.IsComunicazioneProcessataOutType isComunicazioneProcessata(
        @WebParam(name = "applicativo", targetNamespace = "")
        java.lang.String applicativo,
        @WebParam(name = "id", targetNamespace = "")
        long id
    );

    @WebMethod(operationName = "GetElencoNazioni", action = "http://www.eldasoft.it/sil/WSOperazioniGenerali/GetElencoNazioni")    
    public java.lang.String getElencoNazioni();

    @WebMethod(operationName = "GetComunicazione", action = "http://www.eldasoft.it/WSOperazioniGenerali/GetComunicazione")    
    public it.maggioli.eldasoft.gene.ws.GetComunicazioneOutType getComunicazione(
        @WebParam(name = "applicativo", targetNamespace = "")
        java.lang.String applicativo,
        @WebParam(name = "id", targetNamespace = "")
        long id,
        @WebParam(name = "idDocumento", targetNamespace = "")
        java.lang.String idDocumento
    );
    
    @WebMethod(operationName = "UpdateDataLetturaDestinatarioComunicazione", action = "http://www.eldasoft.it/WSOperazioniGenerali/UpdateDataLetturaDestinatarioComunicazione")
    public it.maggioli.eldasoft.gene.ws.ErroreOutType updateDataLetturaDestinatarioComunicazione(
        @WebParam(name = "applicativo", targetNamespace = "")
        java.lang.String applicativo,
        @WebParam(name = "idComunicazione", targetNamespace = "")
        long idComunicazione,
        @WebParam(name = "idDestinatario", targetNamespace = "")
        long idDestinatario
    );

    @WebMethod(operationName = "GetElencoTipiCollaborazione", action = "http://www.eldasoft.it/WSOperazioniGenerali/GetElencoTipiCollaborazione")
    public java.lang.String getElencoTipiCollaborazione();

    @WebMethod(operationName = "GetElencoTipiImpresa", action = "http://www.eldasoft.it/WSOperazioniGenerali/GetElencoTipiImpresa")
    public java.lang.String getElencoTipiImpresa();

    @WebMethod(operationName = "UpdateStatoComunicazioni", action = "http://www.eldasoft.it/WSOperazioniGenerali/UpdateStatoComunicazioni")
    public it.maggioli.eldasoft.gene.ws.ErroreOutType updateStatoComunicazioni(
        @WebParam(name = "comunicazioni", targetNamespace = "")
        java.util.List<it.maggioli.eldasoft.gene.ws.DettaglioComunicazioneType> comunicazioni,
        @WebParam(name = "stato", targetNamespace = "")
        java.lang.String stato
    );

/*    
//    @WebMethod(operationName = "UpdateStatoComunicazioni", action = "http://www.eldasoft.it/WSOperazioniGenerali/UpdateStatoComunicazioni")
//    public it.maggioli.eldasoft.gene.ws.ErroreOutType updateStatoComunicazioni(
//        @WebParam(name = "comunicazioni", targetNamespace = "")
//        it.maggioli.eldasoft.gene.ws.DettaglioComunicazioneType[] comunicazioni,
//        @WebParam(name = "stato", targetNamespace = "")
//        java.lang.String stato
//    );
*/

    @WebMethod(operationName = "UpdateSessionKeyComunicazione", action = "http://www.eldasoft.it/WSOperazioniGenerali/UpdateSessionKeyComunicazione")
    public it.maggioli.eldasoft.gene.ws.ErroreOutType updateSessionKeyComunicazione(
        @WebParam(name = "applicativo", targetNamespace = "")
        java.lang.String applicativo,
        @WebParam(name = "id", targetNamespace = "")
        long id,
        @WebParam(name = "sessionKey", targetNamespace = "")
        java.lang.String sessionKey,
        @WebParam(name = "stato", targetNamespace = "")
        java.lang.String stato
    );

    @WebMethod(operationName = "GetElencoTipiAltraCarica", action = "http://www.eldasoft.it/WSOperazioniGenerali/GetElencoTipiAltraCarica")
    public java.lang.String getElencoTipiAltraCarica();

    @WebMethod(operationName = "SendComunicazione", action = "http://www.eldasoft.it/WSOperazioniGenerali/SendComunicazione")
    public it.maggioli.eldasoft.gene.ws.SendComunicazioneOutType sendComunicazione(
        @WebParam(name = "comunicazione", targetNamespace = "")
        it.maggioli.eldasoft.gene.ws.ComunicazioneType comunicazione
    );

    @WebMethod(operationName = "GetElencoTipiCertificazioneISO", action = "http://www.eldasoft.it/WSOperazioniGenerali/GetElencoTipiCertificazioneISO")
    public java.lang.String getElencoTipiCertificazioneISO();

    @WebMethod(operationName = "GetElencoStatiComunicazione", action = "http://www.eldasoft.it/sil/WSOperazioniGenerali/GetElencoStatiComunicazione")
    public java.lang.String getElencoStatiComunicazione();

    @WebMethod(operationName = "DeleteComunicazione", action = "http://www.eldasoft.it/WSOperazioniGenerali/DeleteComunicazione")
    public it.maggioli.eldasoft.gene.ws.ErroreOutType deleteComunicazione(
        @WebParam(name = "applicativo", targetNamespace = "")
        java.lang.String applicativo,
        @WebParam(name = "id", targetNamespace = "")
        long id
    );

    @WebMethod(operationName = "GetElencoTipiNaturaGiuridica", action = "http://www.eldasoft.it/WSOperazioniGenerali/GetElencoTipiNaturaGiuridica")
    public java.lang.String getElencoTipiNaturaGiuridica();

    @WebMethod(operationName = "GetElencoTipiTitoloTecnico", action = "http://www.eldasoft.it/WSOperazioniGenerali/GetElencoTipiTitoloTecnico")
    public java.lang.String getElencoTipiTitoloTecnico();

    @WebMethod(operationName = "GetElencoTipiAlboProfessionale", action = "http://www.eldasoft.it/WSOperazioniGenerali/GetElencoTipiAlboProfessionale")
    public java.lang.String getElencoTipiAlboProfessionale();
	
}
